#!/usr/bin/perl -wn
#Author: sponge369
use strict;
use Clipboard;
use Term::ANSIColor;


BEGIN {

	@ARGV==1 or warn "Usage: extractPort file_grepeable\n" and exit 1;
	print `clear`;
	@ARGV=grep{-T}@ARGV;
	print color('red');print "\nThe argument must exist and be ASCII TEXT\n" and exit 2 unless @ARGV==1;
	print color('cyan');
	print "\n[] Extracting information...\n\n";
	print color('reset');

}

if ( /\d{1,5}\/open/ ) {

	my @ports=map{$,=",";$_}/(\d{1,5})\/open/gi;
		
	print color('yellow');
	print "\t[] Open Ports: ";
	print color('reset');
	
	print @ports;

	print "\n\n";
	my $copy_ports=join ",", @ports;
	Clipboard->copy_to_all_selections($copy_ports);
	Clipboard->paste() and print color('cyan');print "[] Copied OPEN-Ports to Clipboard.\n";print color('reset');
}

elsif ( /^Host:\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\s+\(\)\s+Status/  ) {

	my @ip=/^Host:\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+\(\)\s+Status/;
	
	print color('yellow');
	print "\t[] Ip_Target: ";
	print color('reset');

	print @ip;
	print "\n";

}
