#!/usr/bin/perl -n
# Port extraction in grepable file format -- 2021-Nov-04 spoNge369
use warnings;
use strict;
use Clipboard;
use Term::ANSIColor;


BEGIN {

	@ARGV == 1 or warn "Usage: extractPorts file_grepeable\n\n" and exit 1;
	print `clear`;
	@ARGV = grep { -T } @ARGV;
	print color('red'); print "\nThe argument must exist and be ASCII TEXT\n\n" and exit 2 unless @ARGV == 1;
	
	print color('cyan'); print "\n[] Extracting information...\n\n";
}

chomp;

if ( /^Host:\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\s+\(\)\s+Status/ ) {

	my @ip = /^Host:\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+\(\)\s+Status/;	

	print color('yellow'); print "\t[] Ip target: "; print color('reset');
	print @ip , "\n\n";
	

}

elsif ( /\d{1,5}\/open/ ) {

	my @ports = map {
		         $, = ",";
		         $_;
	            } /(\d{1,5})\/open/gi;
		
	print color('yellow'); print "\t[] Open ports: "; print color('reset');
	print @ports;
	my $copy_ports = join ",", @ports;
	my @copy_target = /(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/;
	
	my $copy = $copy_ports . " " . $copy_target[0];


	Clipboard->copy_to_all_selections( $copy );
	Clipboard->paste() and print color('cyan'); print "\n\n[] Copied OPEN ports and Ip target to Clipboard.\n\n";

}

